import pandas as pd
import os

# 1. Locate your person2_execution_gaps folder
script_dir = os.path.dirname(os.path.abspath(__file__))

# List of individual finding files generated by your detectors
finding_files = [
    "findings_fast_closures.csv",
    "findings_missing_escalations.csv",
    "findings_repeat_alerts.csv",
    "findings_copy_paste.csv",
    "findings_metric_gaming.csv"
]

all_findings = []

print("Consolidating all Person 2 execution gap findings...")

for filename in finding_files:
    file_path = os.path.join(script_dir, filename)
    if os.path.exists(file_path):
        df_temp = pd.read_csv(file_path)
        print(f"✓ Loaded {len(df_temp)} records from {filename}")
        all_findings.append(df_temp)
    else:
        print(f"⚠️ Warning: {filename} not found. Skipping.")

if all_findings:
    # 2. Combine all dataframes into a single master findings table
    master_df = pd.concat(all_findings, ignore_index=True)
    
    # 3. Enforce Shared Findings Contract Schema exactly
    required_columns = [
        "entity_id", 
        "finding_type", 
        "rule", 
        "value", 
        "peer_baseline", 
        "severity_score", 
        "evidence_ids"
    ]
    
    # Ensure all columns exist, filling missing ones if necessary
    for col in required_columns:
        if col not in master_df.columns:
            master_df[col] = None
            
    master_df = master_df[required_columns]
    
    # 4. Save the master consolidated findings output for Person 3 & 4 (Dashboard & Scoring)
    output_master_path = os.path.join(script_dir, "master_execution_gap_findings.csv")
    master_df.to_csv(output_master_path, index=False)
    
    print(f"\nSuccessfully consolidated {len(master_df)} total execution gap findings!")
    print(f"Master file saved to: {output_master_path}")
    print("\nPreview of Master Findings:")
    print(master_df.head(5).to_string(index=False))
else:
    print("No finding files found to consolidate. Run your individual detectors first!")